<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Данные с виджета Отклонение объема потерь(Блок Балансы)</name>
   <tag></tag>
   <elementGuidId>7e74dbba-2cfa-4561-bea4-e22b65553b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.highcharts-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[17]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>d9082255-f1ae-484a-b793-cd640061d5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>0b229d34-f38a-4cfd-a786-f468a6840687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-root</value>
      <webElementGuid>02e8011d-afe4-45bd-94ec-e7748dd5ca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c4d47184-f9d7-4053-9823-49cf3ab97bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>890</value>
      <webElementGuid>7cf755f4-af31-4ad2-bc60-2296697eb22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>420</value>
      <webElementGuid>4fd34472-3fe9-41f1-b00a-864f9ffe344c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 890 420</value>
      <webElementGuid>08afdaf8-695c-44b9-a5ec-fd979c56c94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017</value>
      <webElementGuid>40bfc4df-0b02-47b9-a431-74ff457501d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-q0em2wy-170&quot;)/svg[@class=&quot;highcharts-root&quot;]</value>
      <webElementGuid>003da89e-d0d8-45e8-aaa9-7c0ab3c86794</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Объем потерь по АО «Тываэнерго» за 2022 год'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>f7f94149-04f1-4ee9-8ae4-600adbc21668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[17]/following::*[name()='svg'][1]</value>
      <webElementGuid>d422f138-5141-45d4-8f82-2988752f4684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017' or . = 'Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017')]</value>
      <webElementGuid>41b267fe-496a-4692-9470-9596b6e774b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
