<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Данные с виджета ПЛАН</name>
   <tag></tag>
   <elementGuidId>4ace5c4c-24e8-4f6a-bdde-51bf3ee4b653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[41]/div[2]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.highcharts-data-labels.highcharts-series-0.highcharts-column-series.highcharts-tracker.highcharts-series-inactive > div.highcharts-label.highcharts-data-label.highcharts-data-label-color-undefined.highcharts-tracker.highcharts-drilldown-data-label > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c0fda05-4cec-4bcc-a3e3-208e3c519985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>966c3f22-2d71-4cc4-bebc-cfb113e29597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>62  </value>
      <webElementGuid>2092712b-d412-4532-867d-ffa358382ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-qdn36k8-87&quot;)/div[@class=&quot;highcharts-data-labels highcharts-series-0 highcharts-column-series highcharts-tracker highcharts-series-inactive&quot;]/div[@class=&quot;highcharts-label highcharts-data-label highcharts-data-label-color-undefined highcharts-tracker highcharts-drilldown-data-label&quot;]/span[1]</value>
      <webElementGuid>d9da13f5-0813-4a64-9467-90780ce0b07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='highcharts-qdn36k8-87']/div/div/span</value>
      <webElementGuid>6e398b0a-ecd9-43ea-b445-8831f8a91f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Динамика'])[2]/following::span[1]</value>
      <webElementGuid>ab04f4c7-551b-4c54-a258-1e15e44d3455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Факт'])[2]/following::span[1]</value>
      <webElementGuid>aa259588-2161-43d1-94ec-a2a94a493fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='↑'])[2]/preceding::span[2]</value>
      <webElementGuid>1d849cc4-60f0-4e8b-8432-817096088fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[21]/preceding::span[4]</value>
      <webElementGuid>77dca9e7-7cd3-418b-8cba-28d967ab48f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='62']/parent::*</value>
      <webElementGuid>5c189ae1-88cc-4274-bdad-d9400f35e64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[41]/div[2]/div/div/div/div/span</value>
      <webElementGuid>ae7a3e23-2101-47da-8a5c-fa878ec5dd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '62  ' or . = '62  ')]</value>
      <webElementGuid>18ad87c5-7c2b-4b79-8494-ffec62969eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
