<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>фильтр ДЗО в Блоке Балансы</name>
   <tag></tag>
   <elementGuidId>e6a2ab65-470f-4c8f-a29d-84bb480a9336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b716a34f34104b64924eef1e74886d04']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b716a34f34104b64924eef1e74886d04 > div.rb-filter-container.not-selectable.rb-filter-multi-selection > div.rb-filter-header-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a93e4e19-2428-4ba3-9287-4ce8b6357682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb-filter-header-container</value>
      <webElementGuid>800de8de-c30f-44c8-b7e1-28099cbeb61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ПАО Россети - РаспредКомплекс - АО «Тываэнерго»</value>
      <webElementGuid>ba05a8a8-ff51-43df-b2d0-7714015c4168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b716a34f34104b64924eef1e74886d04&quot;)/div[@class=&quot;rb-filter-container not-selectable rb-filter-multi-selection&quot;]/div[@class=&quot;rb-filter-header-container&quot;]</value>
      <webElementGuid>1a79df97-2582-47a1-8e0c-c5cb94a60310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b716a34f34104b64924eef1e74886d04']/div/div</value>
      <webElementGuid>4a8780d3-6357-4894-a50e-653089205491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ДЗО'])[1]/following::div[4]</value>
      <webElementGuid>e2631217-18d1-446b-9eb1-1225e2bafbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[5]/following::div[10]</value>
      <webElementGuid>da8b12ca-3e78-4ba7-b698-5b4c69b0eaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[4]/preceding::div[2]</value>
      <webElementGuid>5e8c805a-5ba5-4217-8767-96849026fa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/div</value>
      <webElementGuid>8139f616-3d59-48e7-97a0-0b6a17222691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ПАО Россети - РаспредКомплекс - АО «Тываэнерго»' or . = 'ПАО Россети - РаспредКомплекс - АО «Тываэнерго»')]</value>
      <webElementGuid>07e81b60-279f-48cc-b5d9-19983c508e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
