<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>скролл</name>
   <tag></tag>
   <elementGuidId>05936262-842e-4736-9b4d-8f5fd3c6af9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Прогноз на месяц')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget-header-707564f9aed94e22a446fd3396ebf472 > a.va-widget-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39297339-6e40-479d-ae2d-37cd69b18a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-widget-header</value>
      <webElementGuid>5430a965-2872-48f6-850e-50d02a13dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title.text(), attr: title.linkEnabled() &amp;&amp; title.link().trim() ? { href: title.link().indexOf('http') == 0 ? title.link().trim() : '//' + title.link().trim() } : { href: false }, style: { 'text-align': title.textStyle.alignString(), color: title.textStyle.color(), 'font-size': title.textStyle.fontSize() + 'px', 'font-family': title.textStyle.fontFamily(), 'font-weight': title.textStyle.isBold() ? 'bold' : 'normal', 'font-style': title.textStyle.isItalic() ? 'italic' : 'normal', 'line-height': title.textStyle.lineHeight(), cursor: title.linkEnabled() ? 'pointer' : 'default' }</value>
      <webElementGuid>e549c692-ee13-47eb-bedb-ca94ba5879d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Организация </value>
      <webElementGuid>d81c13d6-b25b-4db0-90e0-1982d937c5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-header-707564f9aed94e22a446fd3396ebf472&quot;)/a[@class=&quot;va-widget-header&quot;]</value>
      <webElementGuid>14bfc3b8-a0b8-4435-a92b-15a971f9d4e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-header-707564f9aed94e22a446fd3396ebf472']/a</value>
      <webElementGuid>6f26d5c8-9c27-4e7a-b50c-c9004ee8a53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Организация')]</value>
      <webElementGuid>e8dffd02-3b36-438f-aa85-d423c0e9e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[22]/following::a[1]</value>
      <webElementGuid>99a18f98-cbb8-48be-9e8b-d103a240ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Динамическая синхронизация фильтров и виджетов'])[1]/following::a[1]</value>
      <webElementGuid>628d2b5d-5809-4a78-bfdd-453b93065f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ПАО Россети - РаспредКомплекс - АО «Чеченэнерго»'])[1]/preceding::a[1]</value>
      <webElementGuid>c435c40b-4bde-421d-83c2-55bb96a879dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[1]/preceding::a[1]</value>
      <webElementGuid>a3ed5b61-018b-4540-b081-333e6017c019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Организация']/parent::*</value>
      <webElementGuid>78985c0e-ce52-4657-bd2b-69221abfef6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[45]/div/a</value>
      <webElementGuid>9d057e91-b14e-42df-b628-42b10d8bbdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Организация ' or . = 'Организация ')]</value>
      <webElementGuid>73f8554a-321d-4264-b359-284c567dee42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
