<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>скролл до фильтра дата</name>
   <tag></tag>
   <elementGuidId>c2d576a9-107e-42ed-ab45-c371f2825f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#widget-header-5b695520ec3542ddafc9b4410a15dece > a.va-widget-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget-header-6a78deb2fc8e416b84939195b00f5c43']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c6c220a6-795b-40c6-9ca4-6e28bcb68a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-widget-header</value>
      <webElementGuid>80e6f407-aa8b-4403-a356-e82fc2e19491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title.text(), attr: title.linkEnabled() &amp;&amp; title.link().trim() ? { href: title.link().indexOf('http') == 0 ? title.link().trim() : '//' + title.link().trim() } : { href: false }, style: { 'text-align': title.textStyle.alignString(), color: title.textStyle.color(), 'font-size': title.textStyle.fontSize() + 'px', 'font-family': title.textStyle.fontFamily(), 'font-weight': title.textStyle.isBold() ? 'bold' : 'normal', 'font-style': title.textStyle.isItalic() ? 'italic' : 'normal', 'line-height': title.textStyle.lineHeight(), cursor: title.linkEnabled() ? 'pointer' : 'default' }</value>
      <webElementGuid>11ceb7c1-d310-4a1d-bfd8-8cc6fe719d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Дата </value>
      <webElementGuid>efe7e59e-a6e7-44ce-a219-23d9c1f4964f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-header-5b695520ec3542ddafc9b4410a15dece&quot;)/a[@class=&quot;va-widget-header&quot;]</value>
      <webElementGuid>f25106c7-c558-4cae-ab08-4345e9ad8bdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-header-5b695520ec3542ddafc9b4410a15dece']/a</value>
      <webElementGuid>1e0cbcdc-748d-422c-b933-9477f1b40400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Дата')]</value>
      <webElementGuid>ec2bc5d3-1c41-4405-bbc7-cf498122d69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[5]/following::a[1]</value>
      <webElementGuid>afc679c5-8977-468e-b707-4f2a296dbc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Применить'])[4]/following::a[1]</value>
      <webElementGuid>c4f4b8c8-0e01-47ca-965c-6bd8e91a2735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Все'])[3]/preceding::a[1]</value>
      <webElementGuid>a7f2aabb-393d-4714-9008-e3255c94e3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[5]/preceding::a[1]</value>
      <webElementGuid>51c6ba60-acb2-4713-8adb-809e682a7750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Дата']/parent::*</value>
      <webElementGuid>54686413-729e-4d7c-822a-30397a62a718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>25e672d6-b9ba-49eb-8902-25e5b472685f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Дата ' or . = 'Дата ')]</value>
      <webElementGuid>61e525db-1dd1-490b-b153-0f36dec6e4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
