<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ПАО Россети</name>
   <tag></tag>
   <elementGuidId>74ec2545-1dd9-4641-ad7d-94f1c4c5eb71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[25]/div[2]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5195de9ab2cf459e8c675d3617047a56 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3d3c356-54c2-416c-8807-1d2e7129a35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5195de9ab2cf459e8c675d3617047a56&quot;)/div[1]</value>
      <webElementGuid>2767f876-273d-4d27-ad24-7deb873ad6e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5195de9ab2cf459e8c675d3617047a56']/div</value>
      <webElementGuid>1adbe746-09a0-40bc-972c-02682ad9a4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div</value>
      <webElementGuid>40025c54-b471-4ed3-aa49-cd541e6bca82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
